### ISSUE TITLE
Where is index.html?

### ISSUE THREAD

**Issue by lzblack** [hillaryyaory/ProjectWebTech#2]

**Comment by hillaryyaory** [comment]
Hi Professor, I did it on visual studio code and I also pushed it but I'm not sure why you can't see it.

**Comment by hillaryyaory** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="Hillary Yaory" content="Hillary Yaory's website's homepage">
    <title>Hillary Yaory's project version 1</title>
    <link rel="stylesheet" href="styles/project1.css" />
</head>
<body>

        <nav>
            <img src="images/hy.png" alt="white icon" height="60">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="work.html">Work</a></li>
                <li><a href="goals.html">Goals</a></li>
                <li><a href="skills.html">Skills</a></li>
                <li><a href="Me.html">Me</a></li>
            </ul>
        </nav>
    <img src="images/hellocolorful.gif" title="hello" alt="hello gif" height="300" class="hello">
<br>
<center>
    I'm Hillary Yaory! I'm a digital product designer! I create art, clothes, websites and much more!
</center>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<footer>
    <ul>
        <li><a href="https://www.linkedin.com/in/hillaryyaory/"><img src="images/linkedin.png" title="linkedin" alt="linkedin" height="60"></a></li>
        <li><a href="http://www.instagram.com/hillaryyaory"><img src="images/instagram.png" title="instagram" alt="instagram" height="60"></a></li>
        <li><a href="mailto: hyaory1@babson.edu"><img src="images/gmail.png" title="gmail" alt="gmail" height="60"></a></li>
    </ul>
    <br>
    <ul>
            Copyrights @ 2022 Hillary Yaory. All rights reserved.
    </ul>
    <br>
    <ul>
        <a href="sitemap.html">Sitemap</a>
    </ul>
  </footer>
</body>
</html>

**Comment by hillaryyaory** [comment]
It says it's committed already. ^

**Comment by lzblack** [comment]
Please move files into root folder(ProjectWebTech).

**Comment by hillaryyaory** [comment]
I think it's already there. Can you help check again? [ProjectWebTech](https://github.com/hillaryyaory/ProjectWebTech)/website-design/

**Comment by hillaryyaory** [comment]
I tried pushing it again and I hope it works.
