### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by Rishav2026** [hillaryyaory/ProjectWebTech#3]
I cannot access your website either through the Cname or through the link you have provided.

**Comment by hillaryyaory** [comment]
There's something wrong with my domain that will take a few days to fix. For now, I think you might have to copy and paste my code to visual studio code.

**Comment by hillaryyaory** [comment]
I'm not sure but I'm going to talk to professor abt my domain tomorrow.

**Comment by hillaryyaory** [comment]
My reviewee also doesn't have a domain and I managed to see his website. You can clone my repository to your vss and see my website.

**Comment by hillaryyaory** [comment]
it's working now.
