### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by laurenngold** [hillaryyaory/ProjectWebTech#4]
Hi Hillary, 

Some technical issues I noticed are listed below: 
- I don't know if it is just on my computer and a glitch on my end. But on the "work" page, I can't see the images for the liberty society merchandise, it just comes up for me as big question marks, so maybe you could look into that!
- On the bottom where you have the LinkedIn, Instagram, and mail with your sitemap. I think it would be better to have it at just the bottom of the page rather than the bottom of the screen regardless of where I am at on your page - it just distracts from the other content on the page. 

Some improvements I think you could make on content are listed below: 
- All of your pages have a lot of images and color and there tends to be a lot of content, however on the goals page, it just has the 6 goals listed and not much else. I feel like maybe you could add like a vision board or like some more descriptions for each goal just so the page has a little more content!
- For all your different work, I feel like you could create a drop down bar under the work tab and have each individual job as its on page just so its less chaotic and easier for the viewer to read!

Obviously these are all just suggestions and I hope they help. 

Your website looks great. 

Best, 

Lauren Gold

**Comment by hillaryyaory** [comment]
Thanks for your comments! They've helped a lot. I've fixed the technical issues (but decided to keep the linkedin, instagram, etc. placing on the footer (as a sticky)). I've added more content for goals, and I deleted the Jemi work I did as I realized it wasn't product designer work, but more UI/UX (so it makes it less chaotic).
